//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleados
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empleados()
        {
            this.Descuentos = new HashSet<Descuentos>();
        }
    
        public int idEmpleado { get; set; }
        public string nombres { get; set; }
        public string cargo { get; set; }
        public System.DateTime fechaIngreso { get; set; }
        public Nullable<decimal> salario { get; set; }
        public string email { get; set; }
        public Nullable<int> pais { get; set; }
        public string logo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Descuentos> Descuentos { get; set; }
        public virtual pais pais1 { get; set; }
    }
}
